apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-audit-service
  namespace: dapr-resiliency
  labels:
    app: customer-audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-audit-service
  template:
    metadata:
      labels:
        app: customer-audit-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "customer-audit-service"
        dapr.io/app-port: "80"
        dapr.io/config: "config"
    spec:
      containers:
        - name: customer-audit-service
          image: "acrkubecon2022.azurecr.io/dapr-resiliency/customer-audit-service:1.0"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80
          imagePullPolicy: Always