apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-loyalty-job
  namespace: dapr-resiliency
  labels:
    app: customer-loyalty-job
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-loyalty-job
  template:
    metadata:
      labels:
        app: customer-loyalty-job
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "customer-loyalty-job"
        dapr.io/app-port: "80"
        dapr.io/config: "config"
    spec:
      containers:
        - name: customer-loyalty-job
          image: "acrkubecon2022.azurecr.io/dapr-resiliency/customer-loyalty-job:1.0"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80
          imagePullPolicy: Always