apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dapr
  namespace: dapr-resiliency
  labels:
    app: frontend-dapr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-dapr
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontend-dapr"          
        dapr.io/app-port: "80"
        dapr.io/config: "config"
      labels:
        app: frontend-dapr
    spec:
      containers:
        - name: frontend-dapr
          image: "acrkubecon2022.azurecr.io/dapr-resiliency/frontend:1.0"
          env:
            - name: "TARGETURL"
              value: "http://localhost:3500/v1.0/invoke/customer-order-service/method/order"
            - name: "INSTANCENAME"
              value: "frontend"
            - name: "PORT"
              value: "80"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-dapr
  namespace: dapr-resiliency
  labels:
    name: frontend-dapr
spec:
  selector:
    app: frontend-dapr
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
---     