apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: checkorders
  namespace: dapr-resiliency
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "*/5 * * * * *"
scopes:
  - customer-loyalty-job