apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-binding
  namespace: dapr-resiliency
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    value: customerorderstore
  - name: accountKey
    secretKeyRef:    
      name: blob-key
      key: blob-key
  - name: containerName
    value: orders
scopes:
  - customer-audit-service
  - customer-loyalty-job