apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-queue
  namespace: dapr-resiliency
spec:
  type: pubsub.kafka
  version: v1  
  metadata:
  - name: brokers
    value: kafka.kafka.svc.cluster.local:9092
  - name: authType
    value: "password"
  - name: saslUsername
    value: user
  - name: saslPassword
    secretKeyRef:
      name: kafka-password
      key: kafka-password
  - name: disableTls 
    value: "true"
scopes:
  - customer-order-service
  - customer-audit-service