apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order-subscription
  namespace: dapr-resiliency
spec:
  topic: order
  route: /order
  pubsubname: order-queue
scopes:
- customer-audit-service